config/routes.rb
Rails.application.routes.draw do
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)


  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }

  namespace :admin do
    resources :users do
      member do
        put 'block'
        put 'unblock'
      end
    end
  end


  root "categories#index"

  resources :categories do
    resources :products 
  end

  resources :bookings, only: [:show, :create]
  get "/my_bookings", to: "bookings#my_bookings"
  post "/payment_completed", to: "bookings#payment_completed"
end

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
<div id="error_explanation">
  <div class="alert alert-danger">
    The form contains <%= pluralize(object.errors.count, "error") %>.
  </div>
  <ul>
  <% object.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
  <% end %>
  </ul>
</div>
<% end %>

app/views/shared/_flash.html.erb
<div>
  <% flash.each do |key, value| %>
    <div class="<%= flash_class(key.to_sym) %> alert-dismissible fade show" role="alert">
      <% unless value == true %>
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        <%= value %>
      <% end %>
    </div>
  <% end %>
</div>

app/views/shared/_footer.html.erb
<div  class="card mt-3">
  <div class="card-header">
  Enjoy Your Day
  </div>
  <div class="card-body">
    <blockquote class="blockquote mb-0">
      <p>A well-known quote, contained in a blockquote element.</p>
      <footer class="blockquote-footer">Someone famous in <cite title="Source Title">Source Title</cite></footer>
    </blockquote>
  </div>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark mt-0">
  <div class="container">
    <a class="navbar-brand" href="<%= root_path%>"><img src="https://static-assets-web.flixcart.com/batman-returns/batman-returns/p/images/fkheaderlogo_exploreplus-44005d.svg" width="160" height="40" title="Flipkart"></a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
        <% if user_signed_in? &&  current_user.seller? || user_signed_in? && current_user.admin? %>
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="<%= root_path%>"><i class="bi bi-house-door"></i></a>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link active dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            <i class="bi bi-person"></i><%= current_user.name %>
            </a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
              <li><%= button_to "Log Out", destroy_user_session_path, class: "dropdown-item", method: :delete %></li>
              <li><a class="dropdown-item" href="<%= edit_user_registration_path %>">Update profile</a></li>
            </ul>
          </li>
        <% elsif user_signed_in? && current_user.customer? %>
        <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="<%= root_path%>"><i class="bi bi-house-door"></i></a>
          </li>
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="<%= my_bookings_path%>">my bookings</i></a>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link active dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            <i class="bi bi-person"></i><%= current_user.name %>
            </a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
              <li><%= button_to "Log Out", destroy_user_session_path, class: "dropdown-item", method: :delete %></li>
              <li><a class="dropdown-item" href="<%= edit_user_registration_path %>">Update profile</a></li>
            </ul>
          </li>
        <% else %>
          <li class="nav-item">
            <a class="nav-link active" href="<%= new_user_session_path %>">Login</a>
          </li>
          <li class="nav-item">
            <a class="nav-link active" href="<%= new_user_registration_path %>">Signup</a>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>