config/routes.rb
Rails.application.routes.draw do
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)


  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }

  namespace :admin do
    resources :users do
      member do
        put 'block'
        put 'unblock'
      end
    end
  end


  root "categories#index"

  resources :categories do
    resources :products 
  end

  resources :bookings, only: [:show, :create]
  get "/my_bookings", to: "bookings#my_bookings"
  post "/payment_completed", to: "bookings#payment_completed"
end

app/models/category.rb
class Category < ApplicationRecord
  has_one_attached :cat_image
  has_many :products , dependent: :destroy
  belongs_to :user

  validates :cat_image, presence: true
  validates :name, presence: true


  def self.ransackable_attributes(auth_object = nil)
    ["cat_image", "created_at", "id", "id_value", "name", "updated_at", "user_id"]
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.all
  end
  
  def show
    @category = Category.find(params[:id])
    @products = Product.where(category_id: @category.id)
  end

  def new
    @category = Category.new
  end

  def create
    @category = current_user.categories.create(category_params)
    if @category.save
      redirect_to root_path
      flash[:success] = 'Category Lounched successfully .'
    else
      render :new, status: :unprocessable_entity
      flash.now[:alert] = 'Something went wrong!'
    end
  end

  def edit
    @category = Category.find(params[:id])
  end

  def update
    @category = Category.find(params[:id])
    if @category.update(category_params)
      redirect_to category_path(@category)
      flash[:success] = 'Category Updated successfully .'
    else
      render :edit, status: :unprocessable_entity
      flash.now[:alert] = 'Something went wrong!'
    end
  end
  
  private

    def category_params
      params.require(:category).permit(:name, :cat_image)
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.erb
<div class="row">
  <div class="col-md-4 mx-auto  my-auto">
    <%= form_with model: category do |form| %>
      <div>
        <%= form.label :name %><br>
        <%= form.text_field :name, class:"form-control" %>
        <%= render 'shared/error_messages', object: form.object %>
      </div>

      <div>
        <%= form.label :category_image %><br>
        <%= form.file_field :cat_image , class:"form-control" %>
      </div>

      <div>
        <%= form.submit class:"btn btn-success mt-4" %>
      </div>
    <% end %>
  </div>
</div>

app/views/categories/edit.html.erb
<h1 style="text-align:center">Edit Category</h1>
<%= render "form", category: @category%>

app/views/categories/index.html.erb
<div class="row">
  <div class="col-md-16 mx-3">
    <h1 class=" mb-4 text-center"><span class="badge rounded-pill bg-dark">CATEGORIES</span></h1>
    <div class="row ms-2">
      <% @categories.each do |category| %>
        <div class="card shadow me-1 mt-2" style="width: 17rem; height: 18rem; ">
          <div class="my-auto mb-5 mx-auto">
            <% if category.cat_image.attached? %>
              <center><%= image_tag category.cat_image, class: "card-img-top mt-2", height:170, width:110 %></center>
            <% end %>
            <div card="card-body">
              <div class="text-center mt-1"><h4 class="card-title"><i><%= category.name%></i></h4></div>
                <center><%= link_to "View products", category_products_path(category), class:"btn btn-outline-success mb-1 mt-2"%></center>
              </div>
            </div>
        </div>
      <% end %>
    </div>
    <% if user_signed_in? && current_user.seller? %>
      <%= link_to "Add new category", new_category_path, class:"btn btn-secondary mt-4" %>
    <% end %>
  </div>
</div>

app/views/categories/new.html.erb
<h1 style="text-align:center">New Category</h1>
<%= render "form", category: @category %>

app/views/categories/show.html.erb
<div class="container">
  <div class="row mt-3">
    <div class="col-lg-12 category_show">
      <h1 class="mt-4"><span class="badge rounded-pill bg-success"><%= @category.name%> Products</h1>
      <div class="row mt-3">
        <% @products.each do |product| %>
          <div class="card shadow me-2 mb-2" style="width: 15rem; height: 24rem; ">
            <div class="my-auto mx-auto ">
              <% if product.cover_image.attached? %>
                <center><%= image_tag product.cover_image, height:200, width:150 %></center>
              <% end %>
              <div card="card-body">
                  <center><strong class="card-title ms-3 mt-3"><%= product.name %></strong></center>
                  <center><strong class="badge rounded-pill bg-dark ">Price: <%= product.price %></strong></center>
                <div>
                  <center><%= link_to "View Details", category_product_path(product.category_id, product) ,class:"btn btn-outline-success mt-3"%><center>
                </div>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

<% if user_signed_in? && current_user.seller?%>
  <div class="row mt-5">
    <div class="col-md-3 ms-auto">
      <%= link_to "create new product", new_category_product_path(@category), class:"btn btn-outline-dark" %>
    </div>
  </div>
<% end %>