config/routes.rb
Rails.application.routes.draw do
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)


  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }

  namespace :admin do
    resources :users do
      member do
        put 'block'
        put 'unblock'
      end
    end
  end


  root "categories#index"

  resources :categories do
    resources :products 
  end

  resources :bookings, only: [:show, :create]
  get "/my_bookings", to: "bookings#my_bookings"
  post "/payment_completed", to: "bookings#payment_completed"
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :category
  belongs_to :user
  has_many :bookings, dependent: :destroy
  has_one_attached :cover_image

  validates :name, presence: true
  validates :price, presence: true
  validates :cover_image, presence: true

  def self.ransackable_attributes(auth_object = nil)
    ["category_id", "cover_image", "created_at", "description", "id", "id_value", "name", "price", "quantity", "remaining_products", "updated_at", "user_id"]
  end
end


# class User < ApplicationRecord
#   has_many :bookings, dependent: :destroy
#   has_many :products, through: :bookings
# end

# class Product < ApplicationRecord
#   belongs_to :category
#   has_many :bookings, dependent: :destroy
#   has_many :users, through: :bookings
# end

# class Booking < ApplicationRecord
#   belongs_to :user
#   belongs_to :product
# end

# class Category < ApplicationRecord
#   has_one_attached :cat_image
#   has_many :products , dependent: :destroy
#   belongs_to :user

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @category = Category.find(params[:category_id])
    if user_signed_in? && current_user.seller? 
      @products = current_user.products.where(category: @category)
    else
      @products = @category.products.all
    end

  end

  def new
    @product = Product.new
  end

  def create
    @product = current_user.products.new(product_params)
    @product.category_id = params[:category_id]
    if @product.save
      redirect_to category_products_path
      flash[:success] = 'Product Lounched successfully .'
    else
      render :new
    end
  end

  def edit
    @product = Product.find(params[:id])
  end

  def update
    @product = Product.find(params[:id])
    if @product.update(product_params)
      redirect_to category_product_path(@product)
      flash[:success] = 'product Updated successfully .'
    else
      render :edit, status: :unprocessable_entity
      flash.now[:alert] = 'Something went wrong!'
    end
  end

  def show
    @product = Product.find(params[:id])
  end

  private

  def product_params
    params.require(:product).permit(:name, :price, :cover_image, :description, :quantity)
  end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<div class="row">
  <div class="col-md-5 mx-auto">
    <div>
      <%= form_with(model: @product, url: category_products_path) do |form| %>
        <%= render 'shared/error_messages', object: form.object %>
        <div class="field mt-3">
          <%= form.label :name %><br>
          <%= form.text_field :name, class:"form-control" %>
        </div>

        <div class="field">
          <%= form.label :description %><br>
          <%= form.text_area :description, class:"form-control" %>
        </div>

        <div class="field">
          <%= form.label :price %>
          <%= form.text_field :price, class:"form-control" %>
        </div>

        <div class="field">
          <%= form.label :cover_image %>
          <%= form.file_field :cover_image, class:"form-control" %>
        </div>

        <div>
          <%= form.label :availability %>
          <%= form.check_box :availability, as: :boolean, label: "availability", class:"ms-3 mt-3 mb-3 " %>
        </div>


        <div class="field">
          <%= form.label :rating %>
          <%= form.text_field :rating, class:"form-control" %>
        </div>

        <div class="field">
          <%= form.label :quantity %>
          <%= form.text_field :quantity, class:"form-control"%>
        </div>

        <div class="field d-grid ">
          <%= form.submit class:"btn btn-success mt-2" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/products/edit.html.erb
<h1 style="text-align:center" class="mt-3">Edit Product Details</h1>
<div class="row">
  <div class="col-md-5 mx-auto">
    <div>
      <%= form_with(model: @product, url: category_product_path) do |form| %>
        <%= render 'shared/error_messages', object: form.object %>
        <div class="field mt-3">
          <%= form.label :name %><br>
          <%= form.text_field :name, class:"form-control" %>
        </div>

        <div class="field">
          <%= form.label :description %><br>
          <%= form.text_area :description, class:"form-control" %>
        </div>

        <div class="field">
          <%= form.label :price %>
          <%= form.text_field :price, class:"form-control" %>
        </div>

        <div class="field">
          <%= form.label :cover_image %>
          <%= form.file_field :cover_image, class:"form-control" %>
        </div>

        <div>
          <%= form.label :availability %>
          <%= form.check_box :availability, as: :boolean, label: "availability", class:"ms-3 mt-3 mb-3 " %>
        </div>


        <div class="field">
          <%= form.label :rating %>
          <%= form.text_field :rating, class:"form-control" %>
        </div>

        <div class="field">
          <%= form.label :quantity %>
          <%= form.text_field :quantity, class:"form-control"%>
        </div>

        <div class="field d-grid ">
          <%= form.submit class:"btn btn-success mt-2" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/products/index.html.erb
<div class="row mt-3 mx-3" >
  <div class="col-lg-12 category_show">
    <h1 class="mt-4"><span class="badge rounded-pill bg-success"><%= @category.name%> Products</h1>
    <div class="row mt-3">
      <% @products.each do |product| %>
        <div class="card shadow me-2 mb-2" style="width: 15rem; height: 24rem; ">
          <div class="my-auto mx-auto ">
            <% if product.cover_image.attached? %>
              <center><%= image_tag product.cover_image, height:200, width:150 %></center>
            <% end %>
            <div card="card-body">
                <center><strong class="card-title ms-3 mt-3"><%= product.name %></strong></center>
                <center><strong class="badge rounded-pill bg-dark ">Price: <%= product.price %></strong></center>
              <div>
                <center><%= link_to "View Details", category_product_path(product.category_id, product) ,class:"btn btn-outline-success mt-3"%><center>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

  <div class="row mt-5">
    <div class="col-md-3 ms-auto">
      <% if user_signed_in? && current_user.seller? %>
        <%= link_to "create new product", new_category_product_path(@category), class:"btn btn-outline-dark" %>
        <%= link_to "Back", root_path , class:"btn btn-outline-dark"%>
      <% else %>
        <%= link_to "Back", root_path , class:"btn btn-outline-dark"%>
      <% end %>
    </div>
  </div>

app/views/products/new.html.erb
<h1 style="text-align:center" class="mt-3">New Product</h1>
<%= render "form", product: @product %>

app/views/products/show.html.erb
<div class="container">
  <div class="card shadow border border-0" style="width: 70rem; height: 40rem;">
    <div class="card shadow border border-0 mt-4">
      <div class="row">
        <div class="col-md-6">
          <div class="mt-2 zoom"><%= image_tag @product.cover_image, height:558, width:470 %></div>
        </div>
          <div class="col-md-6">
            <div class="card-body ">
              <h4 class="card-title bg-dark text-light text-center"><%= @product.name %></h4>
              <h5 class="card-title">price: <%= @product.price %></h5>
              <p class="card-text"><strong>Description: </strong> <%= @product.description %></p>
            </div>
            
            <div class="d-flex flex-column align-items-center justify-content-center">
            
                <%= form_with(url: "/bookings", model: @booking, method: :post, data: {turbo: false}) do |form| %>
                  <%=link_to "Back", category_products_path ,class:"btn btn-primary mt-3"%>
                  <% if user_signed_in? && current_user.seller? %>
                  <%= link_to "Update Details", edit_category_product_path(@product.category_id, @product) ,class:"btn btn-outline-success mt-3"%>
                  <% elsif user_signed_in? && current_user.customer? %>
                    <%= form.hidden_field :product_id, value: @product.id %>
                    <%= form.label :product_count, class:"form-outline text-center" %>
                    <%= form.number_field :no_of_product, min: 1, required: true, class:"form-cntrol" %>
                    <%= form.submit "Buy Now", class: "btn btn-outline-danger btn-lg btn-block mt-3" %>
                  <% elsif user_signed_in? && current_user.admin? %>
                  
                  <% else %>
                    <%= form.hidden_field :product_id, value: @product.id %>
                    <%= form.label :product_count, class:"form-outline text-center" %>
                    <%= form.number_field :no_of_product, min: 1, required: true, class:"form-cntrol" %>
                    <%= form.submit "Buy Now", class: "btn btn-outline-danger btn-lg btn-block mt-3" %>
                  <% end %>
                <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>